### ISSUE TITLE
USB Autosuspend

### ISSUE THREAD

**Issue by lehmanju** [geoffreybennett/scarlett-gen2#11]
I am on Fedora 40 Silverblue and my Scarlett Focusrite Solo Gen 3 stops working regularly. On Archlinux I had no problems but I think power management wasn't enabled there.

After waking up from sleep, dmesg shows that other devices are found and enabled again but not my audio interface.

**Comment by geoffreybennett** [comment]
Hi @lehmanju,

Thanks for your report! Does it only stop working after waking up from sleep? I'll see if I can reproduce the issue on my Fedora 40 system. In the meantime, if you wouldn't mind checking a few things...

Does `dmesg` say anything about the Scarlett during suspend/resume?

Can you check what sort of sleep is happening? What's the output from the following commands:
```
cat /sys/power/state
systemctl status sleep.target suspend.target hibernate.target hybrid-sleep.target
```
?

Can you reproduce the problem by doing `systemctl suspend`?

Also please check the `.../power/control` file for your Scarlett:
```
lsusb -t
grep . /sys/bus/usb/devices/*/power/control
```

Is it set to `auto`? If so, then (as root):
```
echo on > /sys/bus/usb/devices/.../power/control
```
and let me know if that makes any difference.

Thanks,
Geoffrey.

**Comment by lehmanju** [comment]
Thanks for the quick reply. Oddly enough, it seems to work now for the time being after a reboot. 

The issue I experienced did not relate directly to standby/wakeup. Rather, audio suddenly stopped working after a short period of playback. No error messages in dmesg/pipewire, everything showing normal playback but no sound anymore. It also happened after waking up from sleep that's why I suspected autosuspend/power management to be the culprit.

`/power/control` is already set to `on` for the audio interface.

I'd close this issue and reopen it if it happens again. Maybe it's a hardware issue with my USB hubs after all (already ordered a new one).

**Comment by geoffreybennett** [comment]
Could be a hub or cable problem then. Focusrite's recommendations are here:
https://support.focusrite.com/hc/en-gb/articles/206849569-Can-I-use-any-USB-cable-with-my-Focusrite-USB-Interface
https://support.focusrite.com/hc/en-gb/articles/207547015-Troubleshooting-audio-interface-issues

- If you use a USB hub, bypass this and connect your Scarlett directly to a USB port on your computer.
- If you require a USB hub to connect your interface, we recommend using a powered USB hub with a mains power source. If you experience issues we would advise testing different USB hubs to find which works best for your computer and USB devices.
- Connect the interface to its own USB bus (`lsusb -t` on Linux to check)
- Use the cable that comes with the interface.
- If you need to use a cable manufactured by a 3rd party, we recommend any replacement USB cable is under two meters.

Good luck!
