### ISSUE TITLE
QUESTION: Status of the Submission of Vocaster devices

### ISSUE THREAD

**Issue by gelbphoenix** [geoffreybennett/scarlett-gen2#17]
Hey @geoffreybennett!

At first sorry for misusing the Issue for a question.

My question is:
You've stated on the May 11th 2024 that the support for Focusrite Vocaster (One and Two) is submitted upstream. What is the status on that?

I ask especially because the Vocaster would be one of the first Streaming/Podcasting specified devices that would work OOTB™ with the advanced features and be a possible future device for people who want to start in content creation and don't want to or know how to manually install drivers in Linux. (Also the Vocaster is like low in price right now - Vocaster One for €45 at Thomann (That applies for 2024))

**Comment by gelbphoenix** [comment]
Also I should say thanks for maintaining and creating this drivers!

**Comment by geoffreybennett** [comment]
Hi @gelbphoenix,

No problem, I think issues are handy for questions too.

The status is that it was submitted and accepted upstream and will be in Linux 6.10 when that is released in some weeks time. In the meantime (before it's released and then your distro picks it up), you can build the backported driver which is available here: https://github.com/geoffreybennett/scarlett-gen2/releases

Separate to the kernel driver, the GUI needs some updating so you can control the Vocaster's DSP features (compressor and EQ) in a user-friendly way.

Regards,
Geoffrey.

**Comment by paolomainardi** [comment]
Just to be sure, has been released with the 6.10 kernel ?

**Comment by gelbphoenix** [comment]
Yes, Fedora has updated to the 6.10.3 Kernel and the Vocaster One was
recognised without reinstalling the patch.
