### ISSUE TITLE
Scarlett Solo Gen 4 Driver Initialization Issue on Boot

### ISSUE THREAD

**Issue by HarunCelikOtto** [geoffreybennett/scarlett-gen2#19]
Hello,

Thank you for all your hard work!

I have an issue with my Scarlett Solo Gen 4 where when I boot up the PC, the drivers do not correctly initialize. They do however initialize when I either unplug and plug back the device. The device is always connected to the motherboard and has a speaker and headphone constantly connected.

When it isn't working, `Settings > Output Device` shows it as `Digital Output (S/PDIF) - Starship/Matisse HD Audio Controller`. When it works as it should, `Settings > Output Device` shows three options. The (non-working) option mentioned before and the additional two options `Analog Output - Scarlett Solo 4th Gen` & `Digital Output (S/PDIF) - Scarlett Solo 4th Gen` which both work as intended.

Here are relevant parts of the output for `dmesg`.

```
[    1.037550] usb usb5: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.08
[    1.037552] usb usb5: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.037554] usb usb5: Product: xHCI Host Controller
[    1.037555] usb usb5: Manufacturer: Linux 6.8.0-39-generic xhci-hcd
[    1.037556] usb usb5: SerialNumber: 0000:2d:00.3
[    1.273626] usb 5-1: new high-speed USB device number 2 using xhci_hcd
[    1.402140] usb 5-1: New USB device found, idVendor=1235, idProduct=8218, bcdDevice= 8.8c
[    1.402144] usb 5-1: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[    1.402146] usb 5-1: Product: Scarlett Solo 4th Gen
[    1.402148] usb 5-1: Manufacturer: Focusrite
[    1.402150] usb 5-1: SerialNumber: <serial numbers here>
[    7.950317] usb 5-1: Focusrite Scarlett Gen 4 Mixer Driver enabled (pid=0x8218); report any issues to https://github.com/geoffreybennett/scarlett-gen2/issues
[    7.951995] usb 5-1: Scarlett Gen 4 USB response result cmd 2 was -71 expected 100
[    7.952001] usb 5-1: Error initialising Scarlett Gen 4 Mixer Driver: -22
[    7.953198] snd-usb-audio: probe of 5-1:1.0 failed with error -22
[    8.314440] usbcore: registered new interface driver snd-usb-audio
```

I am on Ubuntu, output of `lsb_release -a`.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
```
Here's relevant `uname` outputs.

```
Linux 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by geoffreybennett** [comment]
Hi @HarunCelikOtto,

Please try the 6.10 backported driver: https://github.com/geoffreybennett/scarlett-gen2/releases and please let me know if that fixes it!

Thanks,
Geoffrey.

**Comment by HarunCelikOtto** [comment]
Hello,

I have no idea what changed between when I made the post and your reply, but the issue seems to have resolved without me needing to try the backported driver. I've had multiple boots now where the device was recognized correctly on start up.

I will have more time on the weekend to test things out again, but I'll try to reproduce the issue and see if it comes up. If it does I'll try your suggestion and report back!

Thanks,
Harun

**Comment by HarunCelikOtto** [comment]
Hey Geoffrey,

It looks like I am not able to reproduce the issue. Thanks for the suggestion anyways though!

Best,
Harun

**Comment by geoffreybennett** [comment]
Hi @HarunCelikOtto,

The problem doesn't happen all the time, so I wouldn't be confident that it's fixed for you yet. I've submitted the patch to Ubuntu kernel maintainers, so it should arrive in the next Ubuntu 6.8 kernel update 🤞.

Regards,
Geoffrey.

**Comment by HarunCelikOtto** [comment]
I'll keep my eye (or ears :smile: ) out for the issue to report if something comes up.

Thanks Again!
Harun
