### ISSUE TITLE
Scarlett 18i20 and 18i8 phase incoherence

### ISSUE THREAD

**Issue by jmfriedt** [geoffreybennett/scarlett-gen2#26]
I am not sure whether it is a driver related issue or a hardware issue, but at least I am filing the issue here to ask if anyone is observing the same behaviour.

Using the first three channels of a 18i8 or 18i20 Scarlett sound card, using just straight cables between input and output (hardware loopback configuration) and running the following GNU Radio flowchart

![loopback_snd](https://github.com/user-attachments/assets/ecb9455e-d607-4f95-a4ff-7484444c6e17)

I observe the phase between records of input 1 and input 2 (solid lines) or input 2 and input 3 (dashed lines). Each measurement lasts 10 seconds and is repeated 60 times.

If the emitted audio signal is at 1/6th of the 192 kS/s sampling frequency, the phases look like

![fsdiv6_after_fw_update](https://github.com/user-attachments/assets/caa77edf-3864-4e15-a750-2a71b3290bd2)

At an output frequency of 1/12th of the sampling frequency, the phases look like

![fsdiv12](https://github.com/user-attachments/assets/f128680b-9446-49f8-97a8-d382cd09a1e7)

so more possibilities but still a range of discrete values. This is observed on Debian GNU/Linux running the official 6.10.6-amd64 kernel and also after updating the firmware to 
```
Found firmware version 1583 for Scarlett 2nd Gen 18i8:
  /usr/lib/firmware/scarlett2/scarlett2-1235-8204-1583.bin
Updating Scarlett 2nd Gen 18i8 from firmware version 1076 to 1583
```
Again I am not sure if this is related or not to the driver or the hardware. Thanks.

**Comment by geoffreybennett** [comment]
Hi @jmfriedt,

Your question is unrelated to the Scarlett driver, which has nothing to do with audio I/O. Please see https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md for an explanation.

I can't say that I really understand what you're doing, but some quick calculations...

32kHz signal period = 31.25µs/cycle
0.05 × 31.25µs = 1.5625µs phase difference
192kHz sample rate = 5.21µs/sample
Phase difference = 1.5625/5.12 = 0.3 samples

I can't think how a hardware or a driver issue could cause a discrete range of phase differences that are a fraction of the sample period. I'd suggest you ask your question to some gnuradio people.

Regards,
Geoffrey.

**Comment by jmfriedt** [comment]
OK thanks, I feared so. GNU Radio is only used for generating and recording the samples to compute the phase, so there is hardly any impact on the processing. Since the Y axis is the mixer output involving the (fixed) amplitude signal and the cosine of the phase, the conversion to time is not so obvious, but I'll try to.

The reason I was asking here is that since the CS4272 audio codec is fed at 64x the sampling frequency, I was hoping the driver would be running some clock alignment procedure that could be tuned, but since I read in the FAQ ``Focusrite USB interfaces are “plug-and-play” — they are USB Audio Class Compliant`` I now understand that the issue lies more probably in the hardware itself than the software driving the data exchange.

Thanks for the answer. Best wishes.
