### ISSUE TITLE
Make errors in media.c

### ISSUE THREAD

**Issue by alphonsom** [geoffreybennett/scarlett-gen2#4]
I'm getting two of these errors from media.c on attempting to run make: 

error: initialization of ‘struct device *’ from incompatible pointer type ‘struct device **’ 
Line 38 -  struct device *pcm_dev = &pcm->streams[stream].dev;

Line 166 -  struct device *ctl_dev = &chip->card->ctl_dev;

My kernel is version 6.6.2

**Comment by geoffreybennett** [comment]
Hi @alphonsom,

Thanks for trying it out! I see the problem, and have added an update for 6.6 to the releases page: https://github.com/geoffreybennett/scarlett-gen2/releases/tag/v6.5.11c1

Let me know how that goes please.

Thanks,
Geoffrey.

**Comment by alphonsom** [comment]
Thank @geoffreybennett  for the swift and effective reply. The install throws a few missing bss_file.c errors, but it completes and my Clarett 2pre is now controllable from your control panel. I declare you hero of the republic.

**Comment by geoffreybennett** [comment]
Awesome, thank you! 🙂
